# Generated by Django 5.2.4 on 2025-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="status",
        ),
        migrations.AddField(
            model_name="log",
            name="text",
            field=models.TextField(max_length=50, null=True, verbose_name="Текст"),
        ),
    ]
